### ISSUE TITLE
Python permission errors on running `git-code-debt-generate` as an admin (Windows 10)

### ISSUE THREAD

**Issue by IronicallySerious** [asottile/git-code-debt#137]
<details>
  <summary>Error log</summary>

```shell
D:\Random ❯❯❯ git-code-debt-generate.exe
Traceback (most recent call last):
  File "c:\program files\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Twarit\AppData\Roaming\Python\Python38\Scripts\git-code-debt-generate.exe\__main__.py", line 7, in <module>
  File "C:\Users\Twarit\AppData\Roaming\Python\Python38\site-packages\git_code_debt\generate.py", line 237, in main
    load_data(
  File "C:\Users\Twarit\AppData\Roaming\Python\Python38\site-packages\git_code_debt\generate.py", line 165, in load_data
    insert_metric_changes(db, metrics, metric_mapping, commit)
  File "c:\program files\python38\lib\contextlib.py", line 120, in __exit__
    next(self.gen)
  File "C:\Users\Twarit\AppData\Roaming\Python\Python38\site-packages\git_code_debt\repo_parser.py", line 43, in repo_checked_out
    shutil.rmtree(self.tempdir)
  File "c:\program files\python38\lib\shutil.py", line 737, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "c:\program files\python38\lib\shutil.py", line 610, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "c:\program files\python38\lib\shutil.py", line 610, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "c:\program files\python38\lib\shutil.py", line 610, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "c:\program files\python38\lib\shutil.py", line 615, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "c:\program files\python38\lib\shutil.py", line 613, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\Twarit\\AppData\\Local\\Temp\\tmpy4ix0vm5temp-repo\\.git\\objects\\pack\\pack-a9ab763f347335699a4f44455aec4b2e64f8ab06.idx'
```
  
</details>

Python: 3.8.4
OS: Windows 10

The command was run in an admin PowerShell 7.1.2

**Comment by IronicallySerious** [comment]
Thanks for the fast response!
