### ISSUE TITLE
Multiprocessing eats tracebacks

### ISSUE THREAD

**Issue by ClareCat** [asottile/git-code-debt#75]
Multiprocessing eats the traceback from errors raised in debt metrics which makes it look like the underlying issue might be in git-code-debt and not our metric:

I have redacted some things that are env specific for reasons.
Here is the tb with multiprocessing:
```(venv) master ✗ 🦄  make generate
venv/bin/git-code-debt-generate \
	<codebase> \
	database.db \
	code_debt_metrics
Cloning into '/tmp/tmp8XDrXvtemp-repo'...
done.
Traceback (most recent call last):
  File "venv/bin/git-code-debt-generate", line 11, in <module>
    sys.exit(main())
  File "/code-debt/venv/local/lib/python2.7/site-packages/git_code_debt/generate.py", line 181, in main
    args.skip_default_metrics,
  File "/code-debt/venv/local/lib/python2.7/site-packages/git_code_debt/generate.py", line 98, in load_data
    commits, pool.imap(_get_metrics_inner, mp_args),
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 668, in next
    raise value
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd5 in position 41: ordinal not in range(128)
Makefile:26: recipe for target 'generate' failed
make: *** [generate] Error 1
```

Here is the tb when `pool.imap` is replaced with `map` in `generate.py`:
```(venv) master ✗ 🍪  make generate
venv/bin/git-code-debt-generate \
	<codebase> \
	database.db \
	code_debt_metrics
Cloning into '/tmp/tmpxGxnB9temp-repo'...
done.
Traceback (most recent call last):
  File "venv/bin/git-code-debt-generate", line 11, in <module>
    sys.exit(main())
  File "/code-debt/venv/local/lib/python2.7/site-packages/git_code_debt/generate.py", line 181, in main
    args.skip_default_metrics,
  File "/code-debt/venv/local/lib/python2.7/site-packages/git_code_debt/generate.py", line 98, in load_data
    commits, map(_get_metrics_inner, mp_args),
  File "/code-debt/venv/local/lib/python2.7/site-packages/git_code_debt/generate.py", line 54, in _get_metrics_inner
    return get_metrics(commit, diff, metric_parsers)
  File "/code-debt/venv/local/lib/python2.7/site-packages/git_code_debt/generate.py", line 40, in get_metrics
    return list(get_all_metrics(file_diff_stats))
  File "/code-debt/venv/local/lib/python2.7/site-packages/git_code_debt/generate.py", line 35, in get_all_metrics
    commit, file_diff_stats,
  File "/code-debt/venv/local/lib/python2.7/site-packages/git_code_debt/metrics/base.py", line 39, in get_metrics_from_stat
    if self.line_matches_metric(line, file_diff_stat):
  File "/code-debt/venv/local/lib/python2.7/site-packages/code_debt_metrics/<metric>.py", line 29, in line_matches_metric
    return '<thing> = True' in line
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd5 in position 41: ordinal not in range(128)
Makefile:26: recipe for target 'generate' failed
make: *** [generate] Error 1
```

**Comment by asottile** [comment]
There's two action items out of this:

- revive my `-j1` patch which disables multiprocessing such that this can be easily debugged
- print the trace before reraising into multiprocessing (or switch to `concurrent.futures` / whatever to get this handled better.

**Comment by asottile** [comment]
#85 adds a `--jobs` argument.  I also noticed that tracebacks in multiprocessing functions _are_ presented in python3, so fixing the python2 portion of this is much lower priority.

As a workaround, run with `-j1` to enable debugging + stacktraces.
